# Dockerfile

FROM maven:3.9-eclipse-temurin-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -f CuoiKi_Web_Java_Clothes/pom.xml

FROM tomcat:10.1-jdk11-temurin-focal


ENV JAVA_OPTS="-Xms300m -Xmx300m"
# -------------------------------------

RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build /app/CuoiKi_Web_Java_Clothes/target/ProjectCuoiKi_Clothes-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]