# Dockerfile này đặt TRONG thư mục CuoiKi_Web_Java_Clothes

FROM maven:3.9-eclipse-temurin-11 AS build
WORKDIR /app
COPY . .
# Vì đã set Root Directory, ta chỉ cần gọi pom.xml trực tiếp
RUN mvn clean package -DskipTests

FROM tomcat:10.1-jdk11-temurin-focal
RUN rm -rf /usr/local/tomcat/webapps/*
# Copy file war từ target (không cần tên thư mục cha nữa)
COPY --from=build /app/target/ProjectCuoiKi_Clothes-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]